lighttpd: update to the version 1.4.49

diff --git a/net/lighttpd/files/lighttpd.init b/net/lighttpd/files/lighttpd.init
--- a/net/lighttpd/files/lighttpd.init
+++ b/net/lighttpd/files/lighttpd.init
@@ -1,27 +1,33 @@
 #!/bin/sh /etc/rc.common
 # Copyright (C) 2006-2011 OpenWrt.org
 
-USE_PROCD=1
+START=50
+STOP=50
 
-# Start after the updater resume
-START=80
+USE_PROCD=1
+PROG=/usr/sbin/lighttpd
+
+validate_conf() {
+	$PROG -tt -f /etc/lighttpd/lighttpd.conf >/dev/null 2>&1 || {
+		echo "validation failed"
+		return 1
+	}
+}
 
 start_service() {
-	mkdir -m 0755 -p /var/log/lighttpd
+	user_exists http || user_add http
+	[ -d /var/log/lighttpd ] || {
+		mkdir -m 0775 -p /var/log/lighttpd
+		chgrp www-data /var/log/lighttpd
+	}
+
+	validate_conf || exit 1
+
 	procd_open_instance
-	procd_set_param command /usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf
-	procd_set_param file /etc/lighttpd/lighttpd.conf
-	procd_set_param respawn 120 2 5
+	procd_set_param command $PROG -D -f /etc/lighttpd/lighttpd.conf
 	procd_close_instance
 }
 
-stop_service() {
-	# This ensures that when we are migrating to procd that we kill previous lighttpd version
-	for i in `grep /usr/sbin/lighttpd /proc/[0-9]*/cmdline`; do
-		PID_TO_KILL="`echo $i | sed 's|/proc/\([0-9]\+\)/.*|\1|'`"
-		# Double check not to kill one in LXC
-		if [ \! -f /sys/fs/cgroup/tasks ] || [ -n "`grep "^$PID_TO_KILL\$" /sys/fs/cgroup/tasks`" ]; then
-			kill "$PID_TO_KILL"
-		fi
-	done
+reload_service() {
+	procd_send_signal lighttpd
 }
